title: blog.hxv.me
email: admin@hxv.me
description: Personal blog
baseurl: ""
url: "https://blog.hxv.me"

remote_theme: chesterhow/tale
permalink:    /:year-:month-:day/:title
paginate:     5

plugins:
  - jekyll-paginate
  - jekyll-remote-theme

keep_files:
    - key.pub
